parameters:
  - name: helloWaitSeconds
    type: int
    default: 120

steps:
  - bash: |
      echo "Hello, Welcome to DevOps ABCs World!"
      # sleep for a configurable time
      echo "Sleeping for $(helloWaitSeconds) seconds..."
      sleep $(helloWaitSeconds)
    displayName: "Hello World (sleep=$(helloWaitSeconds)s)"
  - task: CmdLine@2
    displayName: test docker
    inputs:
      script: |
        echo Write your commands here
        echo Hello world
        docker -v
