apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: azure-pipelines-scaledobject
  namespace: __NAMESPACE__
spec:
  scaleTargetRef:
    name: azsh-windows #Target agent deployment name
  minReplicaCount: 1
  maxReplicaCount: 5 #Maximum number of parallel instances
  triggers:
    - type: azure-pipelines
      metadata:
        poolID: "11" #Replace with your agent pool ID
        organizationURLFromEnv: "AZP_URL"
      authenticationRef:
        name: pipeline-trigger-auth
